language: python
matrix:
  include:
    - python: 3.6
      env:
        - TOXENV=py3
    - python: 3.7 # https://docs.travis-ci.com/user/languages/python/#running-python-tests-on-multiple-operating-systems
      dist: xenial # required for Python >= 3.7
      env:
        - TOXENV=py3
        - DEPLOY_TO_PYPI=1
before_install:
  - pip install --upgrade pip
install:
  - pip install tox
script:
  - tox
deploy:
  provider: pypi
  server: https://test.pypi.org/legacy/
  user: luiscoms
  password:
    secure: JqOEzUtXp2+cBrvRIFpSdX1jHArNEo0Wf3huglX5ku5qVKlc7jE8p2OPH11aFjKcsN/NRkupL3gQs/GaZqX0LScMu4VFLXGVsPW0/htcTdUDcwq+mIVgbuDWNa9y4rxGbiW9IIoIbdJZrp/jV9JtwuaB+t6BkE9PkM2nwZBsWaRR/kwLDjP7qxzF2vwGMXHKSnUy7m5dKQ3h3H/ZO1xQNP5vU0/zTyv8xGQF24ftRMCb9ZOyV+G4r7yhU7CUc/XdOVRZLdaSxTpZmoJE5D8YOkuERBkyQ8DAXK4y4R/lnYwA0rGNfzVw1d5unACr+48+imwlNAgPtS5JiRo76boG17h6NrqIx8TjVtK+4GFQijI2HpMvRMql4P4muuckNOUDJJy/oV6Og0loZDXBnCwhjWtnUPS6waPK+IE7/H3bGQq/wU/GLt027L37UOkGXeWTp+hyIMwZ5Pha/1iHBR8wjyg5nC1VpavZI9VL6JGfZu0O+JOhiBxUAIEedCz2aMdDIaenxBgbjjHXyaaxL0L0+iuHjvm7D9D2vNk2LVhpEePG0eiG15QFw8llCsp+lZZKcjdWpzncDmRUyDeVF8Mm1bmt2mbkebaGCVW0zQpx5rSr14cSDUsQ3lwibIxkdY4LzNBwnvJK0AQPS9vgdh4gMuKlUL9YIJ6zv39rndLSf28=
  skip_cleanup: true
  on:
#    tags: true
    condition: $DEPLOY_TO_PYPI = 1
    branch: develop
