language: python
matrix:
  include:
    - python: 3.6
      env:
        - TOXENV=py3
    - python: 3.7 # https://docs.travis-ci.com/user/languages/python/#running-python-tests-on-multiple-operating-systems
      dist: xenial # required for Python >= 3.7
      env:
        - TOXENV=py3
        - DEPLOY_TO_PYPI=1
before_install:
  - pip install --upgrade pip
install:
  - pip install tox
script:
  - tox
deploy:
  provider: pypi
  server: https://test.pypi.org/legacy/
  user: luiscoms
  password:
    secure: k6kMeoaeXquJtLQtFvKrGXgB5eSlSHgPJM/qLFkj51GLSzqKDYk9aX1d0nXBuI1A0ckkxLoPMzDippNpUwHnHdKkNM3wIcXaVRI7EoXQGNQ8UxJVlgDTM/9u8NvYAb+/idA9rMEBX9zkfH5Mskq4qgiCiSx8XxHifwR53g9JinSwbhUPuVP+4vhgPp6piTkQE1WkhbQ76GIH8TVqc7ke/EPwOO5gC5Pp076FhST0sWZxpnZ4NWnfZGoe/IcVbpqAlSoaYR6ykFJX0/sy39+sr/W3MPWV9ayVB217LhuKEp5lK2LTELBaslUCfGDFAaLUOmTtiU+AGVajN48sAqF9TmSJTj2r7JRkZe2fyBF0ZLOP53G+x4dG9wAt3LRotcAL1rLxVzfyRxvUgpLUJefU4vlnFugm1QAL9HXcF83MOWZWlYbBrRBZaxHt+bw+CL1sEs08ew2NBPP9GlD+8mvkZKtxMZP0gER1F8QkAk2potxa8BKDfGuxksLuFR5GC+VHwkP8V/qXmSvhuzGZr8JMabcaRGhiKimBlZruNLvPmEJanGwT/j683TMuNJQqHnAm/mzsVftmzckCVgIDsRozMSX9iOknxeaE2IwEcz+K2swRIoyuYm5PZVuSueH1PU1qAX8H07VfWR/jZ8LG9qO38INPwgcYtbFZYwAoOBAn3B8=
  skip_cleanup: true
  on:
#    tags: true
    condition: $DEPLOY_TO_PYPI = 1
    branch: develop
