language: python
matrix:
  include:
    - python: 3.6
      env:
        - TOXENV=py3
    - python: 3.7 # https://docs.travis-ci.com/user/languages/python/#running-python-tests-on-multiple-operating-systems
      dist: xenial # required for Python >= 3.7
      env:
        - TOXENV=py3
        - DEPLOY_TO_PYPI=1
before_install:
  - pip install --upgrade pip
install:
  - pip install tox
script:
  - tox
deploy:
  provider: pypi
  server: https://test.pypi.org/legacy/
  user: luiscoms
  password:
    secure: p33/gOVWDxwq1MVUug1nmQz1WAfz8RL0oom3q+AMgLVHgWnmDHXCyEmBdgsJap3UP/iFvtUJ0RNNMlZTljuKQv+Iul0h2PDFx+nVACSnXVQw4rvetx0eJgQuanaGUMEGWTu901jjb+OSZYHifCig8cq8E1ZHwl9D8Zr1Nm0TACQXswi9Unusz+fzTZVQ28f9mLfwoTMgsJLrOxV54vJPK92vibJ30e2vHGO8UACa6auYza7jKECe95eGLqVJqkyfCv+RRhGjJZaBz8wj0NJu3lXhkHen43+tW3SnmHhtnXvEL1sJEABAaA+OjvtGnaB3jUJ5WmFkiEqd4A2p6Md3nyqpus7vA2o7sWPs4vayLv8Gq5KBEfLiX5d/ycUmPVm9IIZuZ4nIV7jAN2VshWWpOqjJo7qsTX9I+2Pn4iZKFw7z4LSkJtWAAA+oJZRteqxHczd9CJJCIhOgup6QlDF6k0hKWwlzH0Li3HR8C8m1RxP8qQVT5tR5p1EOzH/lRsfhHBLfAaNOFUrtSW0TXkwtc4IPY0KXLCA5stt8KDlY8IsRtVKBg2Heql6ywnIfqvAqPQTDmhMtl6FN46JNk461R9MCxBhMVJl+4yJPIEv23psUjA05Ix+OtpZXFe9MTeahC8T1H/6pMwn8Ly+/+XXP5jWCHDSsgGzKaN1kFOD43e8=
  skip_cleanup: true
  on:
#    tags: true
    condition: $DEPLOY_TO_PYPI = 1
    branch: develop
