language: python
matrix:
  include:
    - python: 3.6
      env:
        - TOXENV=py3
    - python: 3.7 # https://docs.travis-ci.com/user/languages/python/#running-python-tests-on-multiple-operating-systems
      dist: xenial # required for Python >= 3.7
      env:
        - TOXENV=py3
        - DEPLOY_TO_PYPI=1
before_install:
  - pip install --upgrade pip
install:
  - pip install tox
script:
  - tox
deploy:
  provider: pypi
  server: https://test.pypi.org/legacy/
  user: luiscoms
  password:
    secure: WbifTBesOpHCyRvM8hdXFEritI/YFetqFgfXhlYe1X14maWbzBcyG4d0hwqMtjh9FxqbdnxjDGmXmRXnTKZS/C7WQVv+5LmOckKSyzCdg5cjNrAvyxVnk8//JoFeuiMlvBwoL6XFm2xDzMddNyplVVzdAWcnr/I0eBTsAt1mIwsARP+Ftwq65gyxJEIjEPr09UJiWSCwo/bJ9fY98wAs9jgxnrkhxvoF5F+69UqiCHUFRLadTKrcCS8EMh1X2Kw8dTLxkeezlp6JZc3d1SfkwMUdP6gI43SUvmXEXEGGM1QBkoQKokMcuz5pzfOz8xrpTKHUhF0ywsds4f7gRKaoKmUA8i6R8Fk6La3XDTu1uWYTJo3ILp27o96AiY0cqfEYRDTnL9kM2h6KBIW2UArFj5NnOv3EqVPJii8iF0zJRLZt+c18Rp7iI2uxDySgEWY5u7lRVOmy+/MaXsRBJ97rvBdl1MLcU4BvEstxCKUAZC9DmMxpHwpZL47R/Y30Jz6AmpZ2yAqtZ14KlhfpeUEVSBgHJEYvyem3K0qDgOaxk5pK2KZ28Ksc0p/TL/AV8r+tMJLkjQdDCSY0ju4VD/WbsshGIdHGkyvdsWJF5Om0vZ46isT5RqpyEQgXYrWrAl/4CZAapdBDmDjzSdqtMAWjaC05OUu+OqAt1LuLB+0XaiU=
  skip_cleanup: true
  on:
#    tags: true
    condition: "$DEPLOY_TO_PYPI = 1"
    branch: develop
